server.port=8080

auth-service.url=http://localhost:8081
task-service.url=http://localhost:8082
audit-service.url=http://localhost:8083
analytics-service.url=http://localhost:8084
notification-service.url=http://localhost:8085
comment-service.url=http://localhost:8087
